### ISSUE TITLE
Missing r in YouTube title 

### ISSUE THREAD

**Issue by soegaard** [Gavinok/dotvim#7]
Hi Gavin,

Sorry to misuse the issue tracker, but I couldn't find your email address.

You have a nice video on Racket "[An Intoduction to the Racket Programming Language](https://www.youtube.com/watch?v=n_7drg-R-YY&t=5s)".
But you have forgotten an r in "introduction".

**Comment by Gavinok** [comment]
Thanks for the help. Now fixed
